import type { NextPage } from "next";
import { useProvider } from "wagmi";
import { useEffect, useState } from "react";

const Ens: NextPage = () => {
  const provider = useProvider();
  const [email, setEmail] = useState("");
  const [twitter, setTwitter] = useState("");

  async function test() {
    const resolver = await provider.getResolver("tinaaaaalee.eth");
    const email = await resolver!.getText("email");
    const twitter = await resolver!.getText("com.twitter");
    setEmail(email);
    setTwitter(twitter);
  }

  useEffect(() => {
    test();
  }, [provider]);

  return <div>{email + " " + twitter}</div>;
  // return (
  //   <div className={styles.container}>
  //     <Head>
  //       <title>RainbowKit App</title>
  //       <meta
  //         name="description"
  //         content="Generated by @rainbow-me/create-rainbowkit"
  //       />
  //       <link rel="icon" href="/favicon.ico" />
  //     </Head>

  //     <main className={styles.main}>
  //       <ConnectButton />
  //     </main>
  //   </div>
  // );
};

export default Ens;
